# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
command = "alejandra"
includes = ["*.nix"]

[formatter.go]
command = "gofumpt"
options = ["-w"]
includes = ["*.go"]
excludes = ["*.pb.go$"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.html", "*.json", "*.md", "*.yml", "*.yaml"]
