name: Go package

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'macos-latest', 'windows-latest' ]
        go: [ '1.19' ]
    runs-on: ${{ matrix.os }}
    name: Build (Go ${{ matrix.go }}, OS ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -race -bench='.+' -v ./...