name: Go package

on: [push]

jobs:
  lint:
    runs-on: 'ubuntu-20.04'
    name: Lint
    steps:
      - uses: actions/checkout@v3
      - name: Set up Nix
        uses: cachix/install-nix-action@v21
      - name: Nix Checks
        run: nix flake check